#cloud-config

runcmd:
  # Install Ruby
  - sudo apt update
  - sudo apt install -y ruby-full ruby-bundler build-essential
  # Install MongoDB
  - sudo apt update
  # Install keys
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
  # Add Mongodb repo
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | \
    sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  # Install Mongodb
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
  # Run Mongodb
  - sudo systemctl start mongod
  - sudo systemctl enable mongod
  # Install git
  - sudo apt-get update
  - sudo apt install git
  # Clone repository
  - cd /home/yc-user
  - git clone -b monolith https://github.com/express42/reddit.git
  # Install dependencies
  - cd reddit && bundle install
  # Run server
  - puma -d
