Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
      v.memory = 2048
    end
  
    config.vm.define "dbserver" do |db|
      db.vm.box = "ubuntu/xenial64"
      db.vm.hostname = "dbserver"
      db.vm.network :private_network, ip: "192.168.56.10"

    db.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbooks/site.yml"
        ansible.groups = {
        "db" => ["dbserver"],
        "db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
        }
      end
    end
    
    config.vm.define "appserver" do |app|
      app.vm.box = "ubuntu/xenial64"
      app.vm.hostname = "appserver"
      app.vm.network :private_network, ip: "192.168.56.20"

    app.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbooks/site.yml"
        ansible.groups = {
        "app" => ["appserver"],
        "app:vars" => { "db_host" => "192.168.56.10"}
        }
    ansible.extra_vars = {
        "deploy_user" => "vagrant"
          }
      end
    end
  end
